baseURL: 'http://example.org/'
languageCode: 'fr-fr'
title: 'APE Agrippa Aubigné'
theme: 'hugo-fresh'


googleAnalytics: # Put in your tracking code without quotes like this: UA-XXX for universal tracking or G-XXX analytics v4 tracking
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/fresh.svg
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 112
    # height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Manage. Deploy.
    # Hero subtitle (optional)
    subtitle: Lorem ipsum sit dolor amet is dummy text used by the typography industry
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/*.svg)
    # urls are optional
    clientlogos:
    - logo: systek
      url: https://google.com
    - logo: tribe
      url: https://stefma.github.io/hugo-fresh/
    - logo: kromo
      url: https://github.com/StefMa/hugo-fresh
    - logo: infinite
      url: https://hugo-fresh.vercel.app/
    - logo: gutwork
      url: https://bulma.io/
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Evénements
    url: /#evenements
  - title: Commandes
    url: /commandes
  - title: Contact
  - title: Don
    url: /
    button: true
  section1:
    title: Association des parents d'élèves
    subtitle: Agrippa Aubigné
    tiles:
    - title: L'association
      icon: team
      text: Découvrir l'APE, son fonctionnement et ses misions.
      url: /
      buttonText: Présentation
    - title: Evénements
      icon: party
      text: L'APE est présente à tous les moments forts de l'école.
      url: /
      buttonText: Consulter l'agenda
    - title: Commandes
      icon: cart2
      text: Jus de pommes, sapin...
      url: /
      buttonText: Je commande
  section2:
    title: Prochains événements
    subtitle: 
    features:
    - title: Cueillette & pressage de jus de pommes
      text: ... 
      icon: apple
      buttonText: Je m'inscris
    - title: Marché d'automne
      text: ... 
      icon: market
      buttonText: Je m'inscris
  section3:
    title: Aider sans être membre
    subtitle: Pour un ou plusieurs événements.
    image: illustrations/mockups/fake.png
    buttonText: Donner du temps !
    buttonLink: "#"
  section4:
    title: L'APE a besoin de vous 
    subtitle: 
    items:
    - title: Mission de L'APE
      description: Participer aux sorties scolaires et aux voyages 
    - title: Avec votre aide
      description: Vos idées, vos compétences, un coup de main lors des événements, un gâteau, intégrer l'association
    
   
  section5:
    title: Nous contacter
    subtitle: Vous avez des idées ou des questions ? 
    buttonText: Envoyer
    # action: https://formspree.io/f/<form_id>
    # method: POST
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
